language: python
python:
- 2.7
services:
- postgresql
env:
  global:
  - secure: Cq8PKfG8malw+smIZtQdjHP95XRQipN6WTGaXYE0ZVsaWaNYRuISlvXa402N9SdwAc1b5LdtsR/ROaxjMIzJFRQoHVaUePPKQb17IIf2LruIoHqdWA1yALfDmiOBIAG8dP/d4cdZfTiNbnfnaU36e/r1mCeqmAG5lb/4KxayeNg=
  - secure: N7mvxM8Bb8FG4G9Ae9/gsKw2d1KxqmDBXH1uT+XWslEGkUGbOmraYhEcNSgmrMK0b9ESggkznSkbr04U0RLHkk/nofJz80RmWlY3rBvG/a30qIKgcs/4aG5bycl/oJ8btgvxeMQ61LgKYryhhVfawNcEtnzjG/xlh33ZQcy2KQk=
  - secure: DEjCcAD8RznurFmYC4rj1WYtzF6ekWA5yfQ3QpPUXXV16CIA1qdSJgQEtOhWNNx0znXyzgFCUSXfl8wnNGGhFBzMswnjxOKQeN2cyW7V7H8YDQGz0M2BT59RQJsrRu6ocSc39albI2wUyJzJl+x5S10l7qw7do2uy28vhuIbiRE=
  - secure: YRxxq4eh6/lMYTMkfsyXvDtLHQrf4C9HuJPieWHBEWUDYlCM/xqK1V4trk3vPlX4v5H8JPuRBq5WWO+gJQtaYXjUMqoVj6ne9E9yuxGS8hGPs3gbvnncwdqgUgMMp6DtZ2Xcqyh547e21Sw3a3Hl8TYKzKA6jUqfmiEF09BCqGk=
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- pip install . --use-mirrors
before_script:
- printf "$HEROKU_USER\n$HEROKU_PASSWORD" | heroku login 
- psql -c "create database django_herokuapp_test with owner $USER;" -U postgres
script:
- herokuapp_startproject.py django_herokuapp_test herokuapp_test --noinput
- rm herokuapp_test/requirements.txt
- herokuapp_test/manage.sh test herokuapp --noinput
- herokuapp_test/deploy.sh
- curl --fail http://django-herokuapp-test.herokuapp.com/
after_script:
- heroku apps:delete django-herokuapp-test --confirm django-herokuapp-test
notifications:
  email: false
