language: python
python:
- 2.7
services:
- postgresql
env:
  global:
  - secure: IN9ORGxKYTQQQae5YK9LRfpCBKmvQzARcOAX/XXfQHfyTYEBht6LmWA0boViLQO4On6k8LvPiB9PKCycD6rtTtbPQ97R61asdnvFGwxod72QTdu+NKbtwVgGuRttH769byGUiiY2gXVenbeTKtn1XnD9StWTZj5ghJLUuvbk5cI=
  - secure: CjyWjKfWc73iKmHKIibACC0HnULNZTpFY55elz04lq5NVvBC23gCcBNUhG2+dzF9phdCrhyXyyDb81jDxvSDd3y0/ppOEJsa9iTup+z/LFeY2NGLM5GFiMcdMSHfz7At+usqMwLkJ57T7j+UI0Rp4f9DryIJfyI+M4HLIhQ9b00=
  - secure: HIyF9PPriBNF5wBFZzbUdy+rYIHvZ03kQDjnatx85yJfqiJtiavQAi7COOIZQsTwVQBBM8f567bEHdABbI/gZRSMID9U++kE1IXeKwW6Mi9C2lhAetV0yunyaPIHRA9FfuNlvOOibHYkEEaBhIh9waembi62sMPRsbiL4n+wOLo=
  - PATH=/tmp/heroku-client/bin:$PATH
  matrix:
  - DJANGO=django==1.5.4
  - DJANGO=django==1.6.1
install:
- wget -qO- https://s3.amazonaws.com/assets.heroku.com/heroku-client/heroku-client.tgz
  | tar xz -C /tmp
- pip install $DJANGO --use-mirrors
- pip install . --use-mirrors
before_script:
- psql -c "create database django_herokuapp_test with owner $USER;" -U postgres
script:
- python setup.py test
notifications:
  email: false
