language: python
python:
- 2.7
services:
- postgresql
env:
  global:
  - secure: Cq8PKfG8malw+smIZtQdjHP95XRQipN6WTGaXYE0ZVsaWaNYRuISlvXa402N9SdwAc1b5LdtsR/ROaxjMIzJFRQoHVaUePPKQb17IIf2LruIoHqdWA1yALfDmiOBIAG8dP/d4cdZfTiNbnfnaU36e/r1mCeqmAG5lb/4KxayeNg=
  - secure: N7mvxM8Bb8FG4G9Ae9/gsKw2d1KxqmDBXH1uT+XWslEGkUGbOmraYhEcNSgmrMK0b9ESggkznSkbr04U0RLHkk/nofJz80RmWlY3rBvG/a30qIKgcs/4aG5bycl/oJ8btgvxeMQ61LgKYryhhVfawNcEtnzjG/xlh33ZQcy2KQk=
  - secure: IN9ORGxKYTQQQae5YK9LRfpCBKmvQzARcOAX/XXfQHfyTYEBht6LmWA0boViLQO4On6k8LvPiB9PKCycD6rtTtbPQ97R61asdnvFGwxod72QTdu+NKbtwVgGuRttH769byGUiiY2gXVenbeTKtn1XnD9StWTZj5ghJLUuvbk5cI=
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- pip install . --use-mirrors
before_script:
- psql -c "create database django_herokuapp_test with owner $USER;" -U postgres
script:
- python setup.py test
notifications:
  email: false
